// https://projecteuler.net/problem=2
/*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
import { fibonacci } from '../helper/fibonacci'

function solution (num: number): number {
  let sum = 0
  for (let i = 1; i < num; i++) {
    const result = fibonacci(i)
    if (result > 4000000) {
      return sum
    }
    if (result % 2 === 0) {
      sum += result
    }
  }
  return sum
}

export function problem002 (num: number): number {
  return solution(num)
}
